name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check translation changes
        run: |
          translation_files=("public/locales/es/translation.json")
          translation_files_changed=false

          for file in "${translation_files[@]}"; do
            if [ -f "$file" ]; then
              last_commit=$(git log -1 --format="%ct" -- "$file")
              last_modified=$(stat -c %Y "$file")

              if [ "$last_modified" -gt "$last_commit" ]; then
                translation_files_changed=true
                break
              fi
            fi
          done

          branch=$(git rev-parse --abbrev-ref HEAD)
          remote_branch="origin/$branch"
          version_file_changed=$(git diff --name-only "$remote_branch" -- "src/libs/translations/version.ts" || echo "src/libs/translations/version.ts")

          if [ "$version_file_changed" = "src/libs/translations/version.ts" ]; then
            echo "Version file (src/libs/translations/version.ts) has not been modified."
            exit 1  # Job Failed
          else
            echo "Version file (src/libs/translations/version.ts) has been modified."
            exit 0  # Job Success
          fi
