name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check translation changes
        run: |
          # Check if the version.ts file has changed
          if [[ $(git rev-list --count HEAD) -eq 1 ]]; then
            version_changed=true
          else
            version_changed=$(git diff --name-only HEAD^ HEAD -- src/libs/translations/version.ts)
          fi

          # Check if any translation file has changed
          translations_changed=$(git diff --name-only HEAD^ HEAD -- 'public/locales/**/*.json' | grep -E '^public/locales/.+/translation\.json$' || true)

          # Fail the job if translations changed but version didn't
          if [[ -n $translations_changed && -z $version_changed ]]; then
            echo "Please update the version number"
            exit 1
          fi
