name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check translation changes
        run: |
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            changed_files=$(git diff --name-only HEAD^..HEAD)
          else
            changed_files=$(git ls-tree --name-only HEAD)
          fi

          echo "$changed_files" > changed_files.txt

          if grep -E '^public/locales/(en|es)/translation\.json$' changed_files.txt; then
            current_version=$(grep -oP "(?<=TRANSLATION_VERSION = 'v)\d+" version.ts)
            if [ -z "$current_version" ]; then
              echo "Error: TRANSLATION_VERSION is not set in version.ts"
              exit 1
            fi
            new_version=$((current_version + 1))
            sed -i "s/TRANSLATION_VERSION = 'v$current_version';/TRANSLATION_VERSION = 'v$new_version';/" version.ts
            git add version.ts
            git config user.name "Translation Bot"
            git config user.email "translation-bot@example.com"
            git commit -m "Bump TRANSLATION_VERSION to v$new_version"
            echo "TRANSLATION_VERSION is incremented to v$new_version"
          else
            echo "No translation files changed"
          fi
