name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Get languages list
        id: get_languages
        run: |
          echo "languages=$(ls -d public/locales/*/ | xargs -n1 basename | paste -sd ',')" >> $GITHUB_ENV

      - name: Check for translations changes
        id: translation_changes
        run: |
          echo "translation_changed=false" >> "$GITHUB_ENV"
          IFS=',' read -ra LANGUAGES <<< "${{ env.languages }}"
          git diff --name-only HEAD^ ${{ github.sha }} > changes.txt  
          for lang in "${LANGUAGES[@]}"; do
            if [[ -f "public/locales/$lang/translation.json" ]]; then
               if grep -q "public/locales/$lang/translation.json" changes.txt; then
                echo "Translation file 'public/locales/$lang/translation.json' modified."
                echo "translation_changed=true" >> "$GITHUB_ENV"
              else
                echo "Translation file 'public/locales/$lang/translation.json' not modified."
              fi
            else
              echo "translation_changed=false" >> "$GITHUB_ENV"
              echo "Translation file 'public/locales/$lang/translation.json' not found."
            fi
          done

      - name: Check for version.ts changes
        id: version_changes
        run: |
          git diff --name-only HEAD^ ${{ github.sha }} > changes.txt
          if grep -q "src/libs/translations/version.ts" changes.txt; then
             echo "version_changed=true" >> "$GITHUB_ENV"
             echo "Version file 'src/libs/translations/version.ts' modified."
           else
             echo "version_changed=false" >> "$GITHUB_ENV"
             echo "Version file 'src/libs/translations/version.ts' not modified."
           fi

      - name: Fail or pass job based on changes
        run: |
          if [[ "${{ env.translation_changed }}" == false ]]; then
            echo "Translations did not change - we are good to go"
          else
            if [[ "${{ env.version_changed }}" == true ]]; then
              echo "Version.ts modified along with translation file. Job passed!"
            else
              echo "Version.ts not modified along with translation file. Job failed!"
              exit 1
            fi
          fi
