name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check translation changes
        run: |
          # Check if the version.ts file has changed
          if [[ -n $(git diff --name-only HEAD^ HEAD -- src/libs/translations/version.ts) ]]; then
            version_changed=true
          else
            version_changed=false
          fi

          # Check if any translation file has changed
          translations_changed=false
          while IFS= read -r -d '' file; do
            if [[ -n $(git diff --name-only HEAD^ HEAD -- "$file") ]]; then
              translations_changed=true
              break
            fi
          done < <(find public/locales -name 'translation.json' -print0)

          # Fail the job if translations changed but version didn't
          if [[ $translations_changed == true && $version_changed == false ]]; then
            echo "Please update version number"
            exit 1
          fi
