name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check for translation changes
        id: changes
        run: |
          git diff --name-only HEAD^ ${{ github.sha }} > changes.txt
          if grep -q "public/locales/es/translation.json" changes.txt; then
            if grep -q "src/libs/translations/version.ts" changes.txt; then
              echo "::set-output name=version_changed::true"
            else
              echo "::set-output name=version_changed::false"
            fi
          else
            echo "::set-output name=version_changed::false"
          fi

      - name: Fail or pass job based on changes
        run: |
          if [[ "${{ steps.changes.outputs.version_changed }}" == "true" ]]; then
            echo "Version.ts modified along with translation file. Job passed!"
          else
            echo "Version.ts not modified along with translation file. Job failed!"
            exit 1
          fi
