name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Get language list
        id: get_languages
        run: |
          echo "::set-output name=languages::$(ls -d public/locales/*/ | xargs -n1 basename)"

      - name: Check for translation changes
        id: changes
        run: |
          touch changes.txt
          echo "translation_changed=false" >> "$GITHUB_ENV"
          for lang in ${{ steps.get_languages.outputs.languages }}; do
            if [[ -f "public/locales/$lang/translation.json" ]]; then
              if git log -1 --name-only --oneline -- "public/locales/$lang/translation.json" | grep -q "public/locales/$lang/translation.json"; then
                echo "Translation file 'public/locales/$lang/translation.json' modified."
                echo "translation_changed=true" >> "$GITHUB_ENV"
                echo "$lang" >> changes.txt
              else
                echo "Translation file 'public/locales/$lang/translation.json' not modified."
              fi
            else
              echo "translation_changed=true" >> "$GITHUB_ENV"
              echo "Translation file 'public/locales/$lang/translation.json' not found."
            fi
          done

      - name: Check for version.ts changes
        id: version_changes
        run: |
          git diff --quiet HEAD^ -- "src/libs/translations/version.ts"
          if [[ $? -eq 0 ]]; then
            echo "version_changed=false" >> "$GITHUB_ENV"
            echo "Version file 'src/libs/translations/version.ts' not modified."
          else
            echo "version_changed=true" >> "$GITHUB_ENV"
            echo "Version file 'src/libs/translations/version.ts' modified."
            echo "version" >> changes.txt
          fi

      - name: Fail or pass job based on changes
        run: |
          if [[ "${{ env.translation_changed }}" == false ]]; then
            echo "Translation did not change - we are good to go"
          else
            if [[ "${{ env.version_changed }}" == true ]]; then
              echo "Version.ts modified along with translation file. Job passed!"
            else
              echo "Version.ts not modified along with translation file. Job failed!"
              exit 1
            fi
          fi
