name: Translation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Check translation changes
        run: |
          translation_files=("public/locales/es/translation.json")
          translation_files_changed=false

          for file in "${translation_files[@]}"; do
            if [ -f "$file" ]; then
              last_commit=$(git log -1 --format="%ct" -- "$file")
              last_modified=$(stat -c %Y "$file")

              if [ "$last_modified" -gt "$last_commit" ]; then
                translation_files_changed=true
                break
              fi
            fi
          done

          if [ "$translation_files_changed" = true ]; then
            current_version=$(grep -oP "(?<=TRANSLATION_VERSION = 'v)\d+" src/libs/translations/version.ts)
            if [ -z "$current_version" ]; then
              echo "Error: TRANSLATION_VERSION is not set in version.ts"
              exit 1
            fi
            new_version=$((current_version + 1))
            sed -i "s/TRANSLATION_VERSION = 'v$current_version';/TRANSLATION_VERSION = 'v$new_version';/" src/libs/translations/version.ts
            git add src/libs/translations/version.ts
            git config user.name "Oz's Bot"
            git config user.email "oznasi1@gmail.com"
            git commit -m "Bump TRANSLATION_VERSION to v$new_version"

             # Pull the latest changes from the remote branch
            git pull --rebase origin "$GITHUB_HEAD_REF"

            # Push the commit to the current branch
            git push origin HEAD

            echo "TRANSLATION_VERSION is incremented to v$new_version"
          else
            echo "No translation files changed"
          fi
